CREATE TABLE TB_CLIENTES(
	ID_CLIENTE  NUMERIC(15,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOME VARCHAR(250) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	ENDERECO VARCHAR(250) NULL,
	BAIRRO VARCHAR(250) NULL,
	CIDADE VARCHAR(250) NULL,
	ESTADO CHAR(2) NULL,
	CEP NUMERIC(8) NULL,
	TELEFONE NUMERIC (11) NOT NULL,
	EMAIL VARCHAR(250) NULL	
)

CREATE TABLE TB_SERVICOS(
	ID_SERVICO  NUMERIC(15,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOME_SERVICO VARCHAR(150) NOT NULL,
	VALOR_SERVICO NUMERIC(10,2) NOT NULL,
	TEMPO_GASTO TIME NOT NULL
)

CREATE TABLE TB_AGENDAMENTOS(
	ID_AGENDAMENTO  NUMERIC(15,0) IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_CLIENTE NUMERIC(15,0) FOREIGN KEY REFERENCES TB_CLIENTES(ID_CLIENTE) NOT NULL,
	ID_SERVICO NUMERIC(15,0) FOREIGN KEY REFERENCES TB_SERVICOS(ID_SERVICO) NOT NULL,
	DATA_HORA_AGENDADA DATETIME NOT NULL
)